packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/eslintrc': ^3.3.1
  '@next/eslint-plugin-next': 15.4.6
  '@next/mdx': 15.4.6
  '@tailwindcss/postcss': ^4.1.11
  '@tailwindcss/vite': ^4.1.11
  '@types/node': ^22.17.1
  '@types/react': ^19.1.9
  '@types/react-dom': ^19.1.7
  eslint: 9.33.0
  eslint-config-next: 15.4.6
  next: 15.4.6
  react: ^19.1.1
  react-dom: ^19.1.1
  tailwindcss: ^4.1.11
  typescript: ^5.9.2
  zod: ^4.0.17

ignoredBuiltDependencies:
  - '@parcel/watcher'

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver
