packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/eslintrc': ^3.3.1
  '@next/bundle-analyzer': 15.5.5
  '@next/eslint-plugin-next': 15.5.5
  '@next/mdx': 15.5.5
  '@tailwindcss/postcss': ^4.1.14
  '@tailwindcss/vite': 4.1.14
  '@types/node': ^22.18.10
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  eslint: 9.37.0
  lucide-react: 0.546.0
  next: 15.5.5
  react: 19.2.0
  react-dom: 19.2.0
  tailwindcss: 4.1.14
  type-fest: 5.1.0
  typescript: 5.9.3
  zod: 4.1.12

ignoredBuiltDependencies:
  - '@parcel/watcher'

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver
