packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/eslintrc': ^3.3.1
  '@next/eslint-plugin-next': 15.5.2
  '@next/mdx': 15.5.2
  '@tailwindcss/postcss': ^4.1.12
  '@tailwindcss/vite': ^4.1.12
  '@types/node': ^22.18.0
  '@types/react': ^19.1.12
  '@types/react-dom': ^19.1.8
  eslint: 9.34.0
  eslint-config-next: 15.5.0
  lucide-react: 0.541.0
  next: 15.5.2
  react: ^19.1.1
  react-dom: ^19.1.1
  tailwindcss: ^4.1.12
  typescript: ^5.9.2
  zod: ^4.1.4

ignoredBuiltDependencies:
  - '@parcel/watcher'

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver
