packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/eslintrc': ^3.3.1
  '@next/eslint-plugin-next': 15.5.4
  '@next/mdx': 15.5.4
  '@tailwindcss/postcss': ^4.1.14
  '@tailwindcss/vite': ^4.1.14
  '@types/node': ^22.18.8
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  eslint: 9.36.0
  eslint-config-next: 15.5.4
  lucide-react: 0.544.0
  next: 15.5.4
  react: ^19.2.0
  react-dom: ^19.2.0
  tailwindcss: ^4.1.14
  type-fest: 5.0.1
  typescript: ^5.9.3
  zod: 4.1.11

ignoredBuiltDependencies:
  - '@parcel/watcher'

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver
