packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/eslintrc': ^3.3.1
  '@next/bundle-analyzer': 16.0.1
  '@next/eslint-plugin-next': 16.0.1
  '@next/mdx': 16.0.1
  '@tailwindcss/postcss': ^4.1.16
  '@tailwindcss/vite': ^4.1.16
  '@types/node': ^24.10.0
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  '@vitest/browser': ^4.0.6
  '@vitest/coverage-v8': ^4.0.6
  eslint: ^9.39.1
  lucide-react: 0.552.0
  next: 16.0.1
  react: 19.2.0
  react-dom: 19.2.0
  tailwindcss: ^4.1.16
  type-fest: ^5.2.0
  typescript: ^5.9.3
  vitest: ^4.0.6
  zod: 4.1.12

ignoredBuiltDependencies:
  - '@parcel/watcher'

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver
