packages:
  - apps/*
  - packages/*
catalog:
  # next
  next: 15.3.3
  eslint-config-next: 15.3.3
  '@next/mdx': 15.3.3
  '@next/eslint-plugin-next': 15.3.3
  # react
  react: ^19.1
  react-dom: ^19.1
  '@types/react': ^19.0.10
  '@types/react-dom': ^19.0.4
  # tailwindcss
  tailwindcss: ^4.1.7
  '@tailwindcss/postcss': ^4.1.7
  '@tailwindcss/vite': ^4.1.7
  # etc
  eslint: ^9
  '@eslint/eslintrc': ^3
  typescript: ^5
  '@types/node': ^22
  zod: ^3.25.51
onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver
