packages:
  - apps/*
  - packages/*

catalog:
  # nextjs
  '@next/eslint-plugin-next': 15.4.7
  '@next/mdx': 15.4.7
  eslint-config-next: 15.4.7
  next: 15.4.7
  # tailwindcss
  '@tailwindcss/postcss': ^4.1.12
  '@tailwindcss/vite': ^4.1.12
  tailwindcss: ^4.1.12
  # eslint
  '@eslint/eslintrc': ^3.3.1
  eslint: 9.33.0
  # react
  react: ^19.1.1
  react-dom: ^19.1.1
  '@types/react': ^19.1.10
  '@types/react-dom': ^19.1.7
  # etc
  '@types/node': ^22.17.2
  typescript: ^5.9.2
  zod: ^4.0.17
  'lucide-react': 0.540.0

ignoredBuiltDependencies:
  - '@parcel/watcher'

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver
