packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/eslintrc': ^3.3.1
  '@next/bundle-analyzer': 16.1.1
  '@next/eslint-plugin-next': 16.1.1
  '@next/mdx': 16.1.1
  '@tailwindcss/postcss': ^4.1.18
  '@tailwindcss/vite': ^4.1.18
  '@types/node': 25.0.3
  '@types/react': 19.2.7
  '@types/react-dom': 19.2.3
  '@vitest/browser': ^4.0.16
  '@vitest/coverage-v8': 4.0.16
  eslint: 9.39.2
  lucide-react: 0.562.0
  next: 16.1.1
  react: 19.2.3
  react-dom: 19.2.3
  tailwindcss: ^4.1.18
  type-fest: 5.3.1
  typescript: 5.9.3
  vitest: 4.0.16
  zod: 4.2.1

ignoredBuiltDependencies:
  - '@parcel/watcher'

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - msw
  - sharp
  - unrs-resolver
