packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/eslintrc': ^3.3.1
  '@next/eslint-plugin-next': 15.3.5
  '@next/mdx': 15.3.5
  '@tailwindcss/postcss': ^4.1.11
  '@tailwindcss/vite': ^4.1.11
  '@types/node': ^22.16.2
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  eslint: ^9.30.1
  eslint-config-next: 15.3.5
  next: 15.3.5
  react: ^19.1.0
  react-dom: ^19.1.0
  tailwindcss: ^4.1.11
  typescript: ^5.8.3
  zod: ^4.0.2

ignoredBuiltDependencies:
  - '@parcel/watcher'

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver
