packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/eslintrc': ^3
  '@next/eslint-plugin-next': 15.4.1
  '@next/mdx': 15.4.1
  '@tailwindcss/postcss': ^4
  '@tailwindcss/vite': ^4
  '@types/node': ^22
  '@types/react': ^19.1
  '@types/react-dom': ^19.1
  eslint: ^9
  eslint-config-next: 15.4.1
  next: 15.4.1
  react: ^19.1
  react-dom: ^19.1
  tailwindcss: ^4
  typescript: ^5
  zod: ^4.0.5

ignoredBuiltDependencies:
  - '@parcel/watcher'

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver
