packages:
  - apps/*
  - packages/*

catalog:
  next: 15.3.5
  eslint-config-next: 15.3.5
  '@next/mdx': 15.3.5
  '@next/eslint-plugin-next': 15.3.5
  react: ^19.1
  react-dom: ^19.1
  '@types/react': ^19.1
  '@types/react-dom': ^19.1
  tailwindcss: ^4.1
  '@tailwindcss/postcss': ^4.1
  '@tailwindcss/vite': ^4.1
  eslint: ^9
  '@eslint/eslintrc': ^3
  typescript: ^5
  '@types/node': ^22
  zod: ^3

ignoredBuiltDependencies:
  - '@parcel/watcher'

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver
